// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StripDL;

#nullable disable

namespace StripsDL.Migrations
{
    [DbContext(typeof(StripsContext))]
    [Migration("20250110010816_newModels")]
    partial class newModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AuteurStrip", b =>
                {
                    b.Property<int>("AuteursId")
                        .HasColumnType("int");

                    b.Property<int>("StripsId")
                        .HasColumnType("int");

                    b.HasKey("AuteursId", "StripsId");

                    b.HasIndex("StripsId");

                    b.ToTable("AuteurStrip");
                });

            modelBuilder.Entity("StripsBL.Models.Auteur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Auteur");
                });

            modelBuilder.Entity("StripsBL.Models.Reeks", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Reeks");
                });

            modelBuilder.Entity("StripsBL.Models.Strip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Nr")
                        .HasColumnType("int");

                    b.Property<int>("ReeksId")
                        .HasColumnType("int");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UitgeverijId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReeksId");

                    b.HasIndex("UitgeverijId");

                    b.ToTable("Strip");
                });

            modelBuilder.Entity("StripsBL.Models.Uitgeverij", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Uitgeverij");
                });

            modelBuilder.Entity("StripsDL.Models.AuteurStrip", b =>
                {
                    b.Property<int>("AuteurId")
                        .HasColumnType("int")
                        .HasColumnName("AuteursId")
                        .HasColumnOrder(0);

                    b.Property<int>("StripId")
                        .HasColumnType("int")
                        .HasColumnName("StripsId")
                        .HasColumnOrder(1);

                    b.HasKey("AuteurId", "StripId");

                    b.HasIndex("StripId");

                    b.ToTable("AuteurStrip", "dbo");
                });

            modelBuilder.Entity("AuteurStrip", b =>
                {
                    b.HasOne("StripsBL.Models.Auteur", null)
                        .WithMany()
                        .HasForeignKey("AuteursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StripsBL.Models.Strip", null)
                        .WithMany()
                        .HasForeignKey("StripsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StripsBL.Models.Strip", b =>
                {
                    b.HasOne("StripsBL.Models.Reeks", "Reeks")
                        .WithMany("Strips")
                        .HasForeignKey("ReeksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StripsBL.Models.Uitgeverij", "Uitgeverij")
                        .WithMany()
                        .HasForeignKey("UitgeverijId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reeks");

                    b.Navigation("Uitgeverij");
                });

            modelBuilder.Entity("StripsDL.Models.AuteurStrip", b =>
                {
                    b.HasOne("StripsBL.Models.Auteur", "Auteur")
                        .WithMany()
                        .HasForeignKey("AuteurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StripsBL.Models.Strip", "Strip")
                        .WithMany()
                        .HasForeignKey("StripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auteur");

                    b.Navigation("Strip");
                });

            modelBuilder.Entity("StripsBL.Models.Reeks", b =>
                {
                    b.Navigation("Strips");
                });
#pragma warning restore 612, 618
        }
    }
}
